//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emanet
    {
        public int EmanetID { get; set; }
        public int EmanetKitapId { get; set; }
        public int EmanetVerenId { get; set; }
        public int EmanetAlanId { get; set; }
        public Nullable<System.DateTime> VerilisTarihi { get; set; }
        public Nullable<System.DateTime> GeriAlisTarihi { get; set; }
    
        public virtual Kitaplar Kitaplar { get; set; }
        public virtual Uye Uye { get; set; }
        public virtual Yonetici Yonetici { get; set; }
    }
}
