//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitaplar()
        {
            this.Emanet = new HashSet<Emanet>();
        }
    
        public int KitapID { get; set; }
        public int ISBN { get; set; }
        public string KitapAdi { get; set; }
        public string KitapAciklama { get; set; }
        public int KitapYazarId { get; set; }
        public Nullable<int> Adet { get; set; }
        public int KategoriID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emanet> Emanet { get; set; }
        public virtual Kategori Kategori { get; set; }
        public virtual Yazarlar Yazarlar { get; set; }
    }
}
