//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol
    {
        public int RolID { get; set; }
        public Nullable<int> KullaniciId { get; set; }
        public string RolAdi { get; set; }
    
        public virtual Uye Uye { get; set; }
        public virtual Yonetici Yonetici { get; set; }
    }
}
